/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Post: typeof import('./components/post/Post.vue')['default']
    PostAdding: typeof import('./components/post/Adding.vue')['default']
    PostDeletion: typeof import('./components/post/Deletion.vue')['default']
    PostList: typeof import('./components/post/List.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
