/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/app/Footer.vue')['default']
    Footer: typeof import('./components/app/Footer.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    List: typeof import('./components/post/List.vue')['default']
    Post: typeof import('./components/post/Post.vue')['default']
    PostList: typeof import('./components/post/List.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
